In [1]:
import pandas as pd
from pandas.tools.plotting import scatter_matrix
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn import cross_validation
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import make_classification
from sklearn.cross_validation import cross_val_predict
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from pylab import rcParams
import os
# plot feature importance using built-in function
from numpy import loadtxt
from matplotlib import pyplot
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc

In [2]:
os.chdir("C://Users//rumer//Desktop//8May2017//DataSet")

In [4]:
df=pd.read_csv("w7.csv")
df.columns

Index([u'anon_screen_name', u'QuzAttmptAvg1', u'QuzCount1', u'QuzAvSco1',
       u'QuzLagMean1', u'LecLag1', u'LecCount1', u'VidActCount1', u'eff1',
       u'QuzAttmptAvg2', u'QuzCount2', u'QuzAvSco2', u'QuzLagMean2',
       u'LecLag2', u'LecCount2', u'VidActCount2', u'eff2', u'QuzAttmptAvg3',
       u'QuzCount3', u'QuzAvSco3', u'QuzLagMean3', u'LecLag3', u'LecCount3',
       u'VidActCount3', u'eff3', u'QuzAttmptAvg4', u'QuzCount4', u'QuzAvSco4',
       u'QuzLagMean4', u'LecLag4', u'LecCount4', u'VidActCount4', u'eff4',
       u'QuzAttmptAvg5', u'QuzCount5', u'QuzAvSco5', u'QuzLagMean5',
       u'LecLag5', u'LecCount5', u'VidActCount5', u'eff5', u'QuzAttmptAvg6',
       u'QuzCount6', u'QuzAvSco6', u'QuzLagMean6', u'LecLag6', u'LecCount6',
       u'VidActCount6', u'eff6', u'QuzAttmptAvg7', u'QuzCount7', u'QuzAvSco7',
       u'QuzLagMean7', u'LecLag7', u'LecCount7', u'VidActCount7', u'eff7',
       u'Finalgrade', u'FinalScore', u'Class', u'EngStatus'],
      dtype='object')

In [5]:
df.head()

anon_screen_name  QuzAttmptAvg1  QuzCount1  \
0  012113d6241059a1c191068a899c0396fa3f3ee9       1.500000       25.0   
1  01494288a5ff7efce6e88f56eed694345c5d4bff       0.000000        0.0   
2  02a0c112546f7f05eadaf34efb3548d8702a481f       1.142857       87.5   
3  030541f53670bc50fae8964a78cec71bcfd069b0       0.000000        0.0   
4  04badfbd3e9dfb420065a6ea7cad05db20fa2a5b       0.000000        0.0   

   QuzAvSco1  QuzLagMean1   LecLag1  LecCount1  VidActCount1  eff1  \
0  93.750000       540.00         0        0.0             5     0   
1   0.000000         0.00  14423340       12.5             4     0   
2  88.095714  18787782.86    247320       25.0             3   623   
3   0.000000         0.00         0        0.0            29     0   
4   0.000000         0.00         0        0.0             9     0   

   QuzAttmptAvg2     ...       QuzAvSco7  QuzLagMean7  LecLag7  LecCount7  \
0              0     ...               0            0        0          0   
1              2     ...               0            0        0          0   
2              0     ...               0            0        0          0   
3              0     ...               0            0        0          0   
4              0     ...               0            0        0          0   

   VidActCount7  eff7  Finalgrade  FinalScore         Class    EngStatus  
0             0   181        0.00        Fail  BelowAverage  Time<10Mins  
1             0     0        0.05        Fail  BelowAverage  Time<10Mins  
2             0     0        0.00        Fail  BelowAverage  Time<10Mins  
3             0     0        0.36        Fail  BelowAverage  Time<10Mins  
4             0     0        0.09        Fail  BelowAverage  Time<10Mins  

[5 rows x 61 columns]

In [6]:
df.drop('Finalgrade',1, inplace=True)
df.drop('eff7',1, inplace=True)
df.drop('FinalScore',1, inplace=True)
df.drop('EngStatus',1, inplace=True)

In [7]:
df.columns

Index([u'anon_screen_name', u'QuzAttmptAvg1', u'QuzCount1', u'QuzAvSco1',
       u'QuzLagMean1', u'LecLag1', u'LecCount1', u'VidActCount1', u'eff1',
       u'QuzAttmptAvg2', u'QuzCount2', u'QuzAvSco2', u'QuzLagMean2',
       u'LecLag2', u'LecCount2', u'VidActCount2', u'eff2', u'QuzAttmptAvg3',
       u'QuzCount3', u'QuzAvSco3', u'QuzLagMean3', u'LecLag3', u'LecCount3',
       u'VidActCount3', u'eff3', u'QuzAttmptAvg4', u'QuzCount4', u'QuzAvSco4',
       u'QuzLagMean4', u'LecLag4', u'LecCount4', u'VidActCount4', u'eff4',
       u'QuzAttmptAvg5', u'QuzCount5', u'QuzAvSco5', u'QuzLagMean5',
       u'LecLag5', u'LecCount5', u'VidActCount5', u'eff5', u'QuzAttmptAvg6',
       u'QuzCount6', u'QuzAvSco6', u'QuzLagMean6', u'LecLag6', u'LecCount6',
       u'VidActCount6', u'eff6', u'QuzAttmptAvg7', u'QuzCount7', u'QuzAvSco7',
       u'QuzLagMean7', u'LecLag7', u'LecCount7', u'VidActCount7', u'Class'],
      dtype='object')

In [8]:
df['Class'] = df['Class'].map({'AboveAvgEngaged': 'Engaged', 'AverageEngaged': 'Engaged','BelowAverage':'NotEngaged'})



In [9]:
array=df.values
X = array[:,1:56]
y = array[:,56]


In [10]:
#from sklearn.preprocessing import LabelBinarizer
#lb = LabelBinarizer()
#y = np.array([number[0] for number in lb.fit_transform(y)])


In [11]:
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)
X=normalizedX

In [12]:
validation_size = 0.20
print("Number of records", len(X))
print("Class Distribuition", df.groupby('Class').size())
#plt.plot(df['ActCount-1'])


('Number of records', 10590)
('Class Distribuition', Class
Engaged       4203
NotEngaged    6387
dtype: int64)


In [13]:
seed = 7
X_train, X_test, Y_train, y_test = cross_validation.train_test_split(X, y, test_size=validation_size, random_state=seed)

In [14]:
# Test options and evaluation metric
num_folds = 10
num_instances = len(X_train)
seed = 7
scoring = 'accuracy'
models=[]
models.append(('LR',LogisticRegression()))
models.append(('DTree', DecisionTreeClassifier()))
#models.append(('LDA',LinearDiscriminaantAnalysis()))
models.append(('KNN',KNeighborsClassifier()))
models.append(('CART',DecisionTreeClassifier()))
models.append(('NB',GaussianNB()))
models.append(('SVM',SVC()))
#Evaluate each model
results=[]
names=[]
for name, model in models:
    kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
    cv_results = cross_validation.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean()*100, cv_results.std())
    print(msg)
    # Compare Algorithms

LR: 79.686156 (0.017568)
DTree: 82.507031 (0.016445)
KNN: 79.981037 (0.016469)
CART: 82.247388 (0.013940)
NB: 42.823562 (0.015491)
SVM: 75.637391 (0.017550)


In [15]:
fig = plt.figure()
fig.suptitle('Week-1 to predict Final Grade')
ax = fig.add_subplot(111)
plt.boxplot(results)
plt.ylabel("F1-Score")
plt.xlabel("Classifiers")
ax.set_xticklabels(names)
plt.show()

In [21]:
# Make predictions on validation dataset
# -*- coding: utf-8 -*-
print("Decision Tree")
LR = DecisionTreeClassifier()
LR.fit(X_train, Y_train)
predictions = LR.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))



Decision Tree
0.819641170916
[[ 645  216]
 [ 166 1091]]
             precision    recall  f1-score   support

    Engaged       0.80      0.75      0.77       861
 NotEngaged       0.83      0.87      0.85      1257

avg / total       0.82      0.82      0.82      2118



In [22]:
print("GaussianNB")
LR = GaussianNB()
LR.fit(X_train, Y_train)
predictions = LR.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))


GaussianNB
0.441926345609
[[ 846   15]
 [1167   90]]
             precision    recall  f1-score   support

    Engaged       0.42      0.98      0.59       861
 NotEngaged       0.86      0.07      0.13      1257

avg / total       0.68      0.44      0.32      2118



In [23]:
print("KNeighbors")
LR = KNeighborsClassifier()
LR.fit(X_train, Y_train)
predictions = LR.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))


KNeighbors
0.810670443815
[[ 622  239]
 [ 162 1095]]
             precision    recall  f1-score   support

    Engaged       0.79      0.72      0.76       861
 NotEngaged       0.82      0.87      0.85      1257

avg / total       0.81      0.81      0.81      2118



In [24]:
print("LogisticRegression")
LR = LogisticRegression()
LR.fit(X_train, Y_train)
predictions = LR.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))


LogisticRegression
0.806893295562
[[ 532  329]
 [  80 1177]]
             precision    recall  f1-score   support

    Engaged       0.87      0.62      0.72       861
 NotEngaged       0.78      0.94      0.85      1257

avg / total       0.82      0.81      0.80      2118



In [25]:
print("Support Vector Machine")
LR = SVC()
LR.fit(X_train, Y_train)
predictions = LR.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))


Support Vector Machine
0.766288951841
[[ 388  473]
 [  22 1235]]
             precision    recall  f1-score   support

    Engaged       0.95      0.45      0.61       861
 NotEngaged       0.72      0.98      0.83      1257

avg / total       0.81      0.77      0.74      2118



# RAndom fores t

In [26]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn.cross_validation
import os
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
import sklearn.metrics
 # Feature Importance
from sklearn import datasets
from matplotlib import pyplot as plt
from sklearn.ensemble import ExtraTreesClassifier


In [27]:
os.chdir("C://Users//rumer//Desktop//8May2017//DataSet")

In [28]:
df=pd.read_csv("W7.csv")
df.columns

Index([u'anon_screen_name', u'QuzAttmptAvg1', u'QuzCount1', u'QuzAvSco1',
       u'QuzLagMean1', u'LecLag1', u'LecCount1', u'VidActCount1', u'eff1',
       u'QuzAttmptAvg2', u'QuzCount2', u'QuzAvSco2', u'QuzLagMean2',
       u'LecLag2', u'LecCount2', u'VidActCount2', u'eff2', u'QuzAttmptAvg3',
       u'QuzCount3', u'QuzAvSco3', u'QuzLagMean3', u'LecLag3', u'LecCount3',
       u'VidActCount3', u'eff3', u'QuzAttmptAvg4', u'QuzCount4', u'QuzAvSco4',
       u'QuzLagMean4', u'LecLag4', u'LecCount4', u'VidActCount4', u'eff4',
       u'QuzAttmptAvg5', u'QuzCount5', u'QuzAvSco5', u'QuzLagMean5',
       u'LecLag5', u'LecCount5', u'VidActCount5', u'eff5', u'QuzAttmptAvg6',
       u'QuzCount6', u'QuzAvSco6', u'QuzLagMean6', u'LecLag6', u'LecCount6',
       u'VidActCount6', u'eff6', u'QuzAttmptAvg7', u'QuzCount7', u'QuzAvSco7',
       u'QuzLagMean7', u'LecLag7', u'LecCount7', u'VidActCount7', u'eff7',
       u'Finalgrade', u'FinalScore', u'Class', u'EngStatus'],
      dtype='object')

In [29]:
df['Class'] = df['Class'].map({'AboveAvgEngaged': 'Engaged', 'AverageEngaged': 'Engaged','BelowAverage':'NotEngaged'})

In [30]:
predictors=df[['QuzAttmptAvg1', 'QuzCount1', 'QuzAvSco1',
       'QuzLagMean1', 'LecLag1', 'LecCount1', 'VidActCount1', 'eff1',
       'QuzAttmptAvg2', 'QuzCount2', 'QuzAvSco2', 'QuzLagMean2',
       'LecLag2', 'LecCount2', 'VidActCount2', 'eff2', 'QuzAttmptAvg3',
       'QuzCount3', 'QuzAvSco3', 'QuzLagMean3', 'LecLag3', 'LecCount3',
       'VidActCount3','eff3', 'QuzAttmptAvg4', 'QuzCount4', 'QuzAvSco4',
       'QuzLagMean4', 'LecLag4', 'LecCount4', 'VidActCount4','eff4',
       'QuzAttmptAvg5', 'QuzCount5', 'QuzAvSco5', 'QuzLagMean5',
       'LecLag5', 'LecCount5', 'VidActCount5','eff5', 'QuzAttmptAvg6',
       'QuzCount6', 'QuzAvSco6', 'QuzLagMean6', 'LecLag6', 'LecCount6',
       'VidActCount6','eff6', 'QuzAttmptAvg7', 'QuzCount7', 'QuzAvSco7',
       'QuzLagMean7', 'LecLag7', 'LecCount7', 'VidActCount7']]
X=predictors.as_matrix()

In [31]:
targets=df.Class
Y=np.asarray(targets)

In [32]:
pred_train,pred_test,tar_train,tar_test=train_test_split(predictors,targets,test_size=.4)

In [33]:
pred_train.shape
pred_test.shape
tar_train.shape
tar_test.shape

(4236L,)

In [34]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=25)
classifier=classifier.fit(pred_train,tar_train)

In [35]:
predictions=classifier.predict(pred_test)

In [36]:
sklearn.metrics.confusion_matrix(tar_test,predictions)

array([[1611,   74],
       [  59, 2492]])

In [37]:
sklearn.metrics.accuracy_score(tar_test,predictions)

0.96860245514636445

In [38]:
print(classification_report(tar_test,predictions))

             precision    recall  f1-score   support

    Engaged       0.96      0.96      0.96      1685
 NotEngaged       0.97      0.98      0.97      2551

avg / total       0.97      0.97      0.97      4236



In [39]:
trees=range(25)
accuracy=np.zeros(25)
for idx in range(len(trees)):
    classifier=RandomForestClassifier(n_estimators=idx+1)
    classifier=classifier.fit(pred_train,tar_train)
    predictions=classifier.predict(pred_test)
    accuracy[idx]=sklearn.metrics.accuracy_score(tar_test,predictions)

In [40]:
plt.cla()
plt.plot(trees,accuracy)
plt.show()

# Feature Importance

In [41]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn.cross_validation
import os
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
import sklearn.metrics
 # Feature Importance
from sklearn import datasets
from matplotlib import pyplot as plt
from sklearn.ensemble import ExtraTreesClassifier

In [42]:
os.chdir("C://Users//rumer//Desktop//8May2017//DataSet")

In [43]:
d=predictors
X=d.as_matrix()

In [44]:
targets=df.Class
Y=np.asarray(targets)

In [45]:
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score
scores=[]
for val in range(1,41):
    clf=RandomForestClassifier(n_estimators=val)
    Validated=cross_val_score(clf,X,Y,cv=10)
    scores.append(Validated)
type(scores)

list

In [46]:
clf=RandomForestClassifier(n_estimators=25)
clf.fit(X,Y)
imp=clf.feature_importances_
names=d.columns

imp,names=zip(*sorted(zip(imp,names)))
plt.barh(range(len(names)),imp,align='center')
plt.yticks(range(len(names)),names)
plt.xlabel('Importance of Features')
plt.ylabel('Features')
plt.title('Importance of each feature')
plt.show()